const PRODUCTS_REQUEST = '@@products/PRODUCTS_REQUEST'
const PRODUCTS_SUCCESS = '@@products/PRODUCTS_REQUEST'
const PRODUCTS_FAILURE = '@@products/PRODUCTS_REQUEST'
const RESET_FETCHED = "RESET_FETCHED"
const SET_FETCHED = "SET_FETCHED"
const types = {
    PRODUCTS_FAILURE,
    PRODUCTS_REQUEST,
    PRODUCTS_SUCCESS,
    RESET_FETCHED,
    SET_FETCHED
}
export default types